### ISSUE TITLE
spark container name diff

### ISSUE THREAD

**Issue by liuxiaocs7** [wey-gu/nebula-up#25]
I execute the statement just as follow:

```
# Install Core with Spark Connector, Nebula Algorithm, Nebula Exchange
curl -fsSL nebula-up.siwei.io/all-in-one.sh | bash -s -- v3 spark
```

The container name is `spark-master-1` rather than `spark_master_1`?

![image](https://user-images.githubusercontent.com/42756849/179344174-c61dc697-4706-43fc-b493-5b400c943715.png)

And [here](https://siwei.io/spark-on-nebula-graph/#%E8%BF%9B%E5%85%A5-spark-%E7%8E%AF%E5%A2%83) maybe confusing.

**Comment by wey-gu** [comment]
Thanks, @liuxiaocs7 indeed, the different naming conventions were used in different env from my own ones, I'll do some study(on when/how it differentiated) and fix this soon

**Comment by liuxiaocs7** [comment]
I think the docker-compose.yaml in spark folder has no container name specified for master. If that's true, I'll try to fix it.

```
  master:
    networks:
      - nebula-net
    volumes:
      - '${PWD}/:/root'
    image: 'bde2020/spark-master:2.4.5-hadoop2.7'
```
